0.10 dev
Qitmeer/qitmeer.js pull request #21
Opened 2021-03-01 09:06 UTC by zhangyi999

add coin ID

2021-03-01 09:22 UTC, dindinw requested changes
Instead of master, Please PR to 0.10-dev branch (https://github.com/Qitmeer/qitmeer.js/tree/0.10)

2021-03-01 09:23 UTC, dindinw commented on src/transaction.js
> +    //    0) 2 bytes coinId
//    a) 2 bytes coinId
    //    b) 8 bytes amount

2021-03-01 09:30 UTC, dindinw commented on src/transaction.js
> +    (onlyWitnesses ? 0 : this.vout.reduce(function (sum, output) { return 4 + sum + 8 + varSliceSize(output.script) }, 0)) + // coinId + amount + script
2? 4?

2021-04-05 01:42 UTC, zhangyi999 commented
Need to resubmit

2021-04-05 01:42 UTC, zhangyi999 commented
Need to resubmit

2021-04-05 01:42 UTC, closed without merging